// <auto-generated />
using System;
using AcmeNotas.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AcmeNotas.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20210928185507_generarbase")]
    partial class generarbase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AcmeNotas.App.Dominio.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("AcmeNotas.App.Dominio.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CodDepartamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreDepartamento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("AcmeNotas.App.Dominio.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ciclos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodHorario")
                        .HasColumnType("int");

                    b.Property<string>("CodigoFormador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoTutor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("AcmeNotas.App.Dominio.GrupoEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CodNotas")
                        .HasColumnType("int");

                    b.Property<string>("IdEstudiante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GrupoEstudiantes");
                });

            modelBuilder.Entity("AcmeNotas.App.Dominio.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Dia1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dia2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dia3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoraFinal1")
                        .HasColumnType("int");

                    b.Property<int>("HoraFinal2")
                        .HasColumnType("int");

                    b.Property<int>("HoraFinal3")
                        .HasColumnType("int");

                    b.Property<int>("HoraInicio1")
                        .HasColumnType("int");

                    b.Property<int>("HoraInicio2")
                        .HasColumnType("int");

                    b.Property<int>("HoraInicio3")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("AcmeNotas.App.Dominio.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CodMunicipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdDepartamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreMunicipio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("AcmeNotas.App.Dominio.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("Nota1")
                        .HasColumnType("float");

                    b.Property<double>("Nota2")
                        .HasColumnType("float");

                    b.Property<double>("Nota3")
                        .HasColumnType("float");

                    b.Property<double>("Nota4")
                        .HasColumnType("float");

                    b.Property<double>("Nota5")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("AcmeNotas.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolPersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolPersonaId");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("AcmeNotas.App.Dominio.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CodigoRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreRol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("AcmeNotas.App.Dominio.Estudiante", b =>
                {
                    b.HasBaseType("AcmeNotas.App.Dominio.Persona");

                    b.Property<string>("CodigoEstudiante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdE")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("AcmeNotas.App.Dominio.Formador", b =>
                {
                    b.HasBaseType("AcmeNotas.App.Dominio.Persona");

                    b.Property<string>("CodigoFormador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdF")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Formador");
                });

            modelBuilder.Entity("AcmeNotas.App.Dominio.Tutor", b =>
                {
                    b.HasBaseType("AcmeNotas.App.Dominio.Persona");

                    b.Property<string>("CodigoTutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdT")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Tutor");
                });

            modelBuilder.Entity("AcmeNotas.App.Dominio.Persona", b =>
                {
                    b.HasOne("AcmeNotas.App.Dominio.Rol", "RolPersona")
                        .WithMany()
                        .HasForeignKey("RolPersonaId");

                    b.Navigation("RolPersona");
                });
#pragma warning restore 612, 618
        }
    }
}
